/**
 * Default Role → Permission grants for AgencyOS RBAC.
 *
 * Illustrative default derived from docs/ARCHITECTURE.md §3 (role capability
 * table) — adjust as the formal RBAC spec is ratified. This is the SYSTEM role
 * matrix; organization-specific CUSTOM roles are resolved separately (see
 * `@/types/rbac` `RoleDefinition` / `CustomRoleResolver`) and layered on top.
 *
 * `SUPER_ROLES` bypass permission checks entirely (platform-level override,
 * not org-membership-based) — see `@/lib/rbac/permissions`.
 */

import { ROLES, type Role } from "@/constants/roles";
import { PERMISSIONS, type Permission } from "@/constants/permissions";
import {
  ORGANIZATION_PERMISSIONS,
  type OrganizationPermission,
} from "@/constants/organization-permissions";

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [ROLES.SUPER_ADMIN]: [], // platform-scoped — bypasses checks (see SUPER_ROLES)
  [ROLES.AGENCY_OWNER]: [
    PERMISSIONS.ORG_MANAGE,
    PERMISSIONS.SETTINGS_MANAGE,
    PERMISSIONS.MEMBER_MANAGE,
    PERMISSIONS.LEAD_VIEW,
    PERMISSIONS.LEAD_MANAGE,
    PERMISSIONS.PROPOSAL_MANAGE,
    PERMISSIONS.PROJECT_VIEW,
    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_MANAGE,
    PERMISSIONS.TASK_MANAGE,
    PERMISSIONS.TIME_LOG,
    PERMISSIONS.INVOICE_CREATE,
    PERMISSIONS.INVOICE_VIEW,
    PERMISSIONS.PAYMENT_PAY,
    PERMISSIONS.FINANCE_REPORT_VIEW,
    PERMISSIONS.CMS_MANAGE,
    PERMISSIONS.APPROVAL_DECIDE,
    PERMISSIONS.AI_CONFIGURE,
  ],
  [ROLES.ADMIN]: [
    PERMISSIONS.MEMBER_MANAGE,
    PERMISSIONS.SETTINGS_MANAGE,
    PERMISSIONS.LEAD_VIEW,
    PERMISSIONS.LEAD_MANAGE,
    PERMISSIONS.PROPOSAL_MANAGE,
    PERMISSIONS.PROJECT_VIEW,
    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_MANAGE,
    PERMISSIONS.TASK_MANAGE,
    PERMISSIONS.TIME_LOG,
    PERMISSIONS.INVOICE_CREATE,
    PERMISSIONS.INVOICE_VIEW,
    PERMISSIONS.FINANCE_REPORT_VIEW,
    PERMISSIONS.CMS_MANAGE,
    PERMISSIONS.APPROVAL_DECIDE,
    PERMISSIONS.AI_CONFIGURE,
  ],
  [ROLES.PROJECT_MANAGER]: [
    PERMISSIONS.LEAD_VIEW,
    PERMISSIONS.PROPOSAL_MANAGE,
    PERMISSIONS.PROJECT_VIEW,
    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_MANAGE,
    PERMISSIONS.TASK_MANAGE,
    PERMISSIONS.TIME_LOG,
    PERMISSIONS.INVOICE_VIEW,
    PERMISSIONS.APPROVAL_DECIDE,
  ],
  [ROLES.DEVELOPER]: [
    PERMISSIONS.PROJECT_VIEW,
    PERMISSIONS.TASK_MANAGE,
    PERMISSIONS.TIME_LOG,
  ],
  [ROLES.DESIGNER]: [
    PERMISSIONS.PROJECT_VIEW,
    PERMISSIONS.TASK_MANAGE,
    PERMISSIONS.TIME_LOG,
  ],
  [ROLES.MARKETING_EXECUTIVE]: [PERMISSIONS.CMS_MANAGE, PERMISSIONS.LEAD_VIEW],
  [ROLES.SALES_EXECUTIVE]: [
    PERMISSIONS.LEAD_VIEW,
    PERMISSIONS.LEAD_MANAGE,
    PERMISSIONS.PROPOSAL_MANAGE,
  ],
  [ROLES.FINANCE]: [
    PERMISSIONS.INVOICE_CREATE,
    PERMISSIONS.INVOICE_VIEW,
    PERMISSIONS.FINANCE_REPORT_VIEW,
  ],
  [ROLES.HR]: [PERMISSIONS.MEMBER_MANAGE],
  [ROLES.SUPPORT]: [PERMISSIONS.PROJECT_VIEW],
  [ROLES.CONTRACTOR]: [PERMISSIONS.TASK_MANAGE, PERMISSIONS.TIME_LOG],
  [ROLES.CLIENT_OWNER]: [
    PERMISSIONS.INVOICE_VIEW,
    PERMISSIONS.PAYMENT_PAY,
    PERMISSIONS.APPROVAL_DECIDE,
  ],
  [ROLES.CLIENT_COLLABORATOR]: [PERMISSIONS.INVOICE_VIEW],
  [ROLES.GUEST]: [],
};

export const ROLE_ORGANIZATION_PERMISSIONS: Record<Role, OrganizationPermission[]> = {
  [ROLES.SUPER_ADMIN]: [], // bypasses checks (see SUPER_ROLES)
  [ROLES.AGENCY_OWNER]: [
    ORGANIZATION_PERMISSIONS.ORG_VIEW,
    ORGANIZATION_PERMISSIONS.ORG_UPDATE,
    ORGANIZATION_PERMISSIONS.ORG_DELETE,
    ORGANIZATION_PERMISSIONS.ORG_SETTINGS_MANAGE,
    ORGANIZATION_PERMISSIONS.ORG_BRANDING_MANAGE,
    ORGANIZATION_PERMISSIONS.ORG_FEATURE_MANAGE,
    ORGANIZATION_PERMISSIONS.ORG_BILLING_MANAGE,
    ORGANIZATION_PERMISSIONS.ORG_MEMBER_INVITE,
    ORGANIZATION_PERMISSIONS.ORG_MEMBER_REMOVE,
    ORGANIZATION_PERMISSIONS.ORG_MEMBER_ROLE_MANAGE,
  ],
  // NOT delete / billing — owner-only, per docs/ARCHITECTURE.md §3.
  [ROLES.ADMIN]: [
    ORGANIZATION_PERMISSIONS.ORG_VIEW,
    ORGANIZATION_PERMISSIONS.ORG_UPDATE,
    ORGANIZATION_PERMISSIONS.ORG_SETTINGS_MANAGE,
    ORGANIZATION_PERMISSIONS.ORG_BRANDING_MANAGE,
    ORGANIZATION_PERMISSIONS.ORG_FEATURE_MANAGE,
    ORGANIZATION_PERMISSIONS.ORG_MEMBER_INVITE,
    ORGANIZATION_PERMISSIONS.ORG_MEMBER_REMOVE,
    ORGANIZATION_PERMISSIONS.ORG_MEMBER_ROLE_MANAGE,
  ],
  [ROLES.PROJECT_MANAGER]: [ORGANIZATION_PERMISSIONS.ORG_VIEW],
  [ROLES.DEVELOPER]: [ORGANIZATION_PERMISSIONS.ORG_VIEW],
  [ROLES.DESIGNER]: [ORGANIZATION_PERMISSIONS.ORG_VIEW],
  [ROLES.MARKETING_EXECUTIVE]: [ORGANIZATION_PERMISSIONS.ORG_VIEW],
  [ROLES.SALES_EXECUTIVE]: [ORGANIZATION_PERMISSIONS.ORG_VIEW],
  [ROLES.FINANCE]: [ORGANIZATION_PERMISSIONS.ORG_VIEW],
  [ROLES.HR]: [
    ORGANIZATION_PERMISSIONS.ORG_VIEW,
    ORGANIZATION_PERMISSIONS.ORG_MEMBER_INVITE,
  ],
  [ROLES.SUPPORT]: [ORGANIZATION_PERMISSIONS.ORG_VIEW],
  [ROLES.CONTRACTOR]: [],
  [ROLES.CLIENT_OWNER]: [],
  [ROLES.CLIENT_COLLABORATOR]: [],
  [ROLES.GUEST]: [],
};

/** Roles that bypass ALL permission checks (platform scope, not org-membership-based). */
export const SUPER_ROLES: Role[] = [ROLES.SUPER_ADMIN];
