/**
 * Service Catalog — the definitive list of what the agency sells.
 * Real data module (not a database yet): every marketing page reads from this
 * single source. Shaped to match docs/DATABASE.md so a future API can replace
 * it without changing any consuming component.
 *
 * `priceFrom` (amountMinor = paise, currency = INR) is the numeric floor of
 * each package/add-on's range — the exact value the checkout pricing engine
 * (`@/lib/pricing-engine`) calculates against. `priceLabel` remains the
 * display string shown on marketing pages; the two are kept in sync by hand
 * until a backend makes `priceFrom` authoritative.
 */

import type { CatalogService } from "@/types/catalog";
import { PRICING_MODELS, PACKAGE_TIERS } from "@/constants/catalog";

export const CATALOG_SERVICES: CatalogService[] = [
  {
    slug: "web-development",
    categoryId: "design-engineering",
    index: "01",
    title: "Website Development",
    tagline: "Websites engineered to convert.",
    summary:
      "Fast, secure, high-converting websites and web applications built on a modern stack — from luxury brand sites to complex SaaS platforms.",
    outcome: "Sites that load in under a second and turn visitors into revenue.",
    capabilities: [
      "Corporate & Business Websites",
      "Enterprise Websites",
      "Landing Pages",
      "Startup & SaaS Platforms",
      "Portfolio & Luxury Brand Sites",
      "Ecommerce, Shopify & WooCommerce",
      "Headless & Custom CMS",
      "Booking Systems & CRM Integrations",
      "API & Dashboard Development",
      "Admin Panels & Web Apps",
      "AI-powered Websites",
      "Redesign & Speed Optimization",
      "Technical SEO, Accessibility & Security",
    ],
    deliverables: [
      "Design-to-code, pixel-perfect build",
      "Headless CMS the team can actually use",
      "Analytics, events & conversion tracking",
      "Core Web Vitals in the green",
      "Staging + production CI/CD pipeline",
    ],
    outcomes: [
      { metric: "0.9s", label: "median load time" },
      { metric: "+38%", label: "avg. conversion lift" },
      { metric: "98+", label: "Lighthouse score" },
    ],
    process: [
      { title: "Architect", detail: "Information architecture, tech selection and a performance budget agreed up front." },
      { title: "Design", detail: "A conversion-first interface with a reusable component system." },
      { title: "Build", detail: "Type-safe, tested code shipped through a preview-per-branch pipeline." },
      { title: "Launch & tune", detail: "Analytics, A/B tests and post-launch optimization sprints." },
    ],
    technologies: ["Next.js", "React", "TypeScript", "Tailwind", "Node", "Sanity", "Shopify", "Vercel", "AWS"],
    accent: "royal",
    pricingModel: PRICING_MODELS.TIERED,
    packages: [
      {
        id: "web-development-basic",
        serviceSlug: "web-development",
        tier: PACKAGE_TIERS.BASIC,
        name: "Basic",
        tagline: "A premium, fast marketing site — live in weeks.",
        priceLabel: "₹5,999",
        priceFrom: { amountMinor: 599900, currency: "INR" },
        cadence: "per project",
        features: [
          "Up to 5-page marketing site",
          "Custom design (templated system)",
          "Mobile-responsive, on-page SEO",
          "Analytics & conversion tracking",
          "2 weeks post-launch support",
        ],
        ctaLabel: "Choose Basic",
      },
      {
        id: "web-development-standard",
        serviceSlug: "web-development",
        tier: PACKAGE_TIERS.STANDARD,
        name: "Standard",
        tagline: "A fully custom site with a CMS your team will love.",
        priceLabel: "₹19,999",
        priceFrom: { amountMinor: 1999900, currency: "INR" },
        cadence: "per project",
        featured: true,
        features: [
          "Everything in Basic",
          "Up to 10 pages, fully custom design system",
          "CMS integration your team can run",
          "Core Web Vitals optimization",
          "4 weeks post-launch support",
        ],
        ctaLabel: "Choose Standard",
      },
      {
        id: "web-development-premium",
        serviceSlug: "web-development",
        tier: PACKAGE_TIERS.PREMIUM,
        name: "Premium",
        tagline: "A full web app or platform, built to scale.",
        priceLabel: "₹49,999",
        priceFrom: { amountMinor: 4999900, currency: "INR" },
        cadence: "per project",
        features: [
          "Everything in Standard",
          "Web app / customer portal",
          "Headless CMS & API integrations",
          "Advanced motion & interactions",
          "8 weeks post-launch support",
        ],
        ctaLabel: "Choose Premium",
      },
    ],
    addons: [
      {
        id: "web-development-addon-landing-page",
        serviceSlug: "web-development",
        name: "Extra landing page",
        description: "An additional conversion-focused landing page, designed and built to match your system.",
        priceLabel: "₹15k each",
        priceFrom: { amountMinor: 1500000, currency: "INR" },
      },
      {
        id: "web-development-addon-cro",
        serviceSlug: "web-development",
        name: "Ongoing CRO program",
        description: "Monthly experimentation and conversion-rate optimization after launch.",
        priceLabel: "₹40k/mo",
        priceFrom: { amountMinor: 4000000, currency: "INR" },
      },
    ],
    comparisonRows: [
      { feature: "Custom design system", values: [false, true, true] },
      { feature: "CMS integration", values: [false, true, true] },
      { feature: "Analytics & conversion tracking", values: [true, true, true] },
      { feature: "Web app / customer portal", values: [false, false, true] },
      { feature: "Headless CMS & API integrations", values: [false, false, true] },
      { feature: "Core Web Vitals optimization", values: [false, true, true] },
      { feature: "Post-launch support window", values: ["2 weeks", "4 weeks", "8 weeks"] },
    ],
  },
  {
    slug: "mobile-apps",
    categoryId: "design-engineering",
    index: "02",
    title: "Mobile App Development",
    tagline: "Apps people keep on their home screen.",
    summary:
      "Native and cross-platform mobile apps with the polish of a flagship product — from booking and fintech to marketplaces and IoT.",
    outcome: "Products that ship fast, scale cleanly and earn five-star reviews.",
    capabilities: [
      "Android & iOS (Native)",
      "Flutter & React Native",
      "Cross-platform Apps",
      "Enterprise & Booking Apps",
      "Healthcare & Fintech",
      "Food Delivery & Taxi",
      "Education & Marketplace",
      "Inventory, CRM & ERP",
      "AI, IoT & Wearables",
    ],
    deliverables: [
      "Native-grade UX on both platforms",
      "Offline-first architecture",
      "App Store & Play Store submission",
      "Crash reporting & analytics",
      "Scalable backend & API layer",
    ],
    outcomes: [
      { metric: "4.8★", label: "avg. store rating" },
      { metric: "60fps", label: "buttery interactions" },
      { metric: "-45%", label: "time-to-market" },
    ],
    process: [
      { title: "Define", detail: "Product strategy, user journeys and an MVP scope that ships." },
      { title: "Prototype", detail: "Interactive prototypes validated with real users before we write code." },
      { title: "Engineer", detail: "Modular, testable code with continuous delivery to TestFlight & Play." },
      { title: "Scale", detail: "Performance monitoring, feature releases and growth loops." },
    ],
    technologies: ["Swift", "Kotlin", "Flutter", "React Native", "Firebase", "Supabase", "GraphQL", "AWS"],
    accent: "violet",
    pricingModel: PRICING_MODELS.TIERED,
    packages: [
      {
        id: "mobile-apps-basic",
        serviceSlug: "mobile-apps",
        tier: PACKAGE_TIERS.BASIC,
        name: "Basic",
        tagline: "A focused MVP on the platform your users are on.",
        priceLabel: "₹24,999",
        priceFrom: { amountMinor: 2499900, currency: "INR" },
        cadence: "per project",
        features: [
          "Single platform (iOS or Android)",
          "Core user flows",
          "Basic analytics",
          "App Store / Play Store submission",
          "2 weeks post-launch support",
        ],
        ctaLabel: "Choose Basic",
      },
      {
        id: "mobile-apps-standard",
        serviceSlug: "mobile-apps",
        tier: PACKAGE_TIERS.STANDARD,
        name: "Standard",
        tagline: "One codebase, both platforms, offline-ready.",
        priceLabel: "₹59,999",
        priceFrom: { amountMinor: 5999900, currency: "INR" },
        cadence: "per project",
        featured: true,
        features: [
          "Everything in Basic",
          "iOS + Android (Flutter / React Native)",
          "Offline-first architecture",
          "Push notifications & crash reporting",
          "4 weeks post-launch support",
        ],
        ctaLabel: "Choose Standard",
      },
      {
        id: "mobile-apps-premium",
        serviceSlug: "mobile-apps",
        tier: PACKAGE_TIERS.PREMIUM,
        name: "Premium",
        tagline: "A platform with a backend built to scale.",
        priceLabel: "₹1,49,999",
        priceFrom: { amountMinor: 14999900, currency: "INR" },
        cadence: "per project",
        features: [
          "Everything in Standard",
          "Custom backend & API layer",
          "Admin dashboard",
          "Advanced analytics & experimentation",
          "8 weeks post-launch support",
        ],
        ctaLabel: "Choose Premium",
      },
    ],
    addons: [
      {
        id: "mobile-apps-addon-web-companion",
        serviceSlug: "mobile-apps",
        name: "Web companion app",
        description: "A complementary web app sharing your mobile app's backend and design system.",
        priceLabel: "from ₹19,999",
        priceFrom: { amountMinor: 1999900, currency: "INR" },
      },
      {
        id: "mobile-apps-addon-aso",
        serviceSlug: "mobile-apps",
        name: "App Store Optimization sprint",
        description: "Store listing, keywords and creative optimized to lift organic installs.",
        priceLabel: "₹60k",
        priceFrom: { amountMinor: 6000000, currency: "INR" },
      },
    ],
    comparisonRows: [
      { feature: "iOS + Android coverage", values: [false, true, true] },
      { feature: "Offline-first architecture", values: [false, true, true] },
      { feature: "Push notifications", values: [false, true, true] },
      { feature: "Custom backend & API layer", values: [false, false, true] },
      { feature: "Admin dashboard", values: [false, false, true] },
      { feature: "Crash reporting & analytics", values: [true, true, true] },
      { feature: "Post-launch support window", values: ["2 weeks", "4 weeks", "8 weeks"] },
    ],
  },
  {
    slug: "ui-ux-design",
    categoryId: "design-engineering",
    index: "03",
    title: "UI / UX Design",
    tagline: "Interfaces that feel inevitable.",
    summary:
      "Research-led product design and design systems that make complex products feel effortless — and beautiful enough to sell themselves.",
    outcome: "Clarity that lifts activation, retention and lifetime value.",
    capabilities: [
      "UX Research & IA",
      "User Flows & Wireframes",
      "High-fidelity Design",
      "Interactive Prototypes",
      "Design Systems & Libraries",
      "Accessibility & Usability Testing",
      "Motion & Micro-interactions",
      "Dashboard & SaaS Design",
      "Mobile, Tablet & Desktop UI",
    ],
    deliverables: [
      "End-to-end product design in Figma",
      "A living, documented design system",
      "Clickable prototypes for every flow",
      "Accessibility audit (WCAG 2.2 AA)",
      "Design-to-dev handoff specs",
    ],
    outcomes: [
      { metric: "+52%", label: "activation rate" },
      { metric: "-31%", label: "support tickets" },
      { metric: "AA", label: "accessibility grade" },
    ],
    process: [
      { title: "Discover", detail: "Interviews, analytics and competitive teardown to find the real problem." },
      { title: "Frame", detail: "Flows, IA and low-fidelity structure aligned to business goals." },
      { title: "Craft", detail: "High-fidelity UI, motion and a scalable component system." },
      { title: "Validate", detail: "Usability testing and iteration until the numbers move." },
    ],
    technologies: ["Figma", "Framer", "Rive", "Storybook", "Maze", "Principle"],
    accent: "cyan",
    pricingModel: PRICING_MODELS.TIERED,
    packages: [
      {
        id: "ui-ux-design-basic",
        serviceSlug: "ui-ux-design",
        tier: PACKAGE_TIERS.BASIC,
        name: "Basic",
        tagline: "A focused design sprint for your core flows.",
        priceLabel: "₹5,999",
        priceFrom: { amountMinor: 599900, currency: "INR" },
        cadence: "per project",
        features: [
          "UX audit",
          "Wireframes for core flows",
          "High-fidelity UI (up to 5 screens)",
          "1 revision round",
        ],
        ctaLabel: "Choose Basic",
      },
      {
        id: "ui-ux-design-standard",
        serviceSlug: "ui-ux-design",
        tier: PACKAGE_TIERS.STANDARD,
        name: "Standard",
        tagline: "A full product design system, tested with real users.",
        priceLabel: "₹17,999",
        priceFrom: { amountMinor: 1799900, currency: "INR" },
        cadence: "per project",
        featured: true,
        features: [
          "Everything in Basic",
          "Full product design (all flows)",
          "Reusable design system",
          "Interactive prototype & usability testing",
          "2 revision rounds",
        ],
        ctaLabel: "Choose Standard",
      },
      {
        id: "ui-ux-design-premium",
        serviceSlug: "ui-ux-design",
        tier: PACKAGE_TIERS.PREMIUM,
        name: "Premium",
        tagline: "An embedded design partner for the full product.",
        priceLabel: "₹44,999",
        priceFrom: { amountMinor: 4499900, currency: "INR" },
        cadence: "per project",
        features: [
          "Everything in Standard",
          "Accessibility audit (WCAG 2.2 AA)",
          "Motion & micro-interaction design",
          "Dev handoff specs",
          "Unlimited revisions during engagement",
        ],
        ctaLabel: "Choose Premium",
      },
    ],
    addons: [
      {
        id: "ui-ux-design-addon-screens",
        serviceSlug: "ui-ux-design",
        name: "Additional screen batch",
        description: "10 more high-fidelity screens designed to the same system.",
        priceLabel: "₹50k",
        priceFrom: { amountMinor: 5000000, currency: "INR" },
      },
      {
        id: "ui-ux-design-addon-retainer",
        serviceSlug: "ui-ux-design",
        name: "Design system maintenance",
        description: "Ongoing upkeep and expansion of your design system as the product grows.",
        priceLabel: "₹35k/mo",
        priceFrom: { amountMinor: 3500000, currency: "INR" },
      },
    ],
    comparisonRows: [
      { feature: "Reusable design system", values: [false, true, true] },
      { feature: "Interactive prototype", values: [false, true, true] },
      { feature: "Usability testing", values: [false, true, true] },
      { feature: "Accessibility audit (WCAG 2.2 AA)", values: [false, false, true] },
      { feature: "Motion & micro-interactions", values: [false, false, true] },
      { feature: "Revision rounds", values: ["1", "2", "Unlimited"] },
    ],
  },
  {
    slug: "branding",
    categoryId: "brand-growth",
    index: "04",
    title: "Branding",
    tagline: "Identity that commands a premium.",
    summary:
      "Strategic brand systems — from naming and logo to a full visual language — that make you impossible to confuse with anyone else.",
    outcome: "A brand that lets you charge more and be remembered.",
    capabilities: [
      "Brand Identity & Strategy",
      "Logo & Typography",
      "Color & Visual Systems",
      "Packaging & Presentation",
      "Pitch Decks",
      "Social Branding",
      "Brand Guidelines",
      "Marketing Assets",
      "Creative Direction",
    ],
    deliverables: [
      "Brand strategy & positioning",
      "Logo suite & typographic system",
      "Comprehensive brand guidelines",
      "Launch-ready marketing assets",
      "Templates your team can run with",
    ],
    outcomes: [
      { metric: "3.2×", label: "brand recall" },
      { metric: "+27%", label: "pricing power" },
      { metric: "1", label: "unmistakable identity" },
    ],
    process: [
      { title: "Position", detail: "Audience, category and the one idea you'll own." },
      { title: "Express", detail: "Logo, type, color and voice built around that idea." },
      { title: "System", detail: "Guidelines and assets so the brand stays consistent everywhere." },
      { title: "Activate", detail: "Rollout across product, web and social." },
    ],
    technologies: ["Illustrator", "Figma", "After Effects", "Blender", "InDesign"],
    accent: "royal",
    pricingModel: PRICING_MODELS.TIERED,
    packages: [
      {
        id: "branding-basic",
        serviceSlug: "branding",
        tier: PACKAGE_TIERS.BASIC,
        name: "Basic",
        tagline: "A clean, confident identity starter.",
        priceLabel: "₹4,999",
        priceFrom: { amountMinor: 499900, currency: "INR" },
        cadence: "per project",
        features: [
          "Logo & typography",
          "Color system",
          "Basic brand guidelines",
          "2 concepts presented",
        ],
        ctaLabel: "Choose Basic",
      },
      {
        id: "branding-standard",
        serviceSlug: "branding",
        tier: PACKAGE_TIERS.STANDARD,
        name: "Standard",
        tagline: "A full brand system, ready to launch.",
        priceLabel: "₹14,999",
        priceFrom: { amountMinor: 1499900, currency: "INR" },
        cadence: "per project",
        featured: true,
        features: [
          "Everything in Basic",
          "Brand strategy & positioning",
          "Comprehensive brand guidelines",
          "Launch marketing assets",
          "3 concepts presented",
        ],
        ctaLabel: "Choose Standard",
      },
      {
        id: "branding-premium",
        serviceSlug: "branding",
        tier: PACKAGE_TIERS.PREMIUM,
        name: "Premium",
        tagline: "Brand system plus a guided rollout.",
        priceLabel: "₹34,999",
        priceFrom: { amountMinor: 3499900, currency: "INR" },
        cadence: "per project",
        features: [
          "Everything in Standard",
          "Packaging & presentation design",
          "Pitch deck",
          "Social brand templates",
          "Creative direction on rollout",
        ],
        ctaLabel: "Choose Premium",
      },
    ],
    addons: [
      {
        id: "branding-addon-concept",
        serviceSlug: "branding",
        name: "Extra concept direction",
        description: "An additional distinct creative direction to choose from.",
        priceLabel: "₹25k",
        priceFrom: { amountMinor: 2500000, currency: "INR" },
      },
      {
        id: "branding-addon-social-templates",
        serviceSlug: "branding",
        name: "Social media templates pack",
        description: "A set of on-brand, ready-to-use templates for your social channels.",
        priceLabel: "₹20k",
        priceFrom: { amountMinor: 2000000, currency: "INR" },
      },
    ],
    comparisonRows: [
      { feature: "Brand strategy & positioning", values: [false, true, true] },
      { feature: "Comprehensive brand guidelines", values: [true, true, true] },
      { feature: "Launch marketing assets", values: [false, true, true] },
      { feature: "Packaging & presentation design", values: [false, false, true] },
      { feature: "Pitch deck", values: [false, false, true] },
      { feature: "Concepts presented", values: ["2", "3", "3 + creative direction"] },
    ],
  },
  {
    slug: "digital-marketing",
    categoryId: "brand-growth",
    index: "05",
    title: "Digital Marketing",
    tagline: "Compounding, organic growth.",
    summary:
      "SEO, content and lifecycle marketing engineered as a system — so traffic, leads and pipeline grow month over month.",
    outcome: "A predictable engine for qualified demand.",
    capabilities: [
      "SEO & Technical SEO",
      "Local SEO",
      "Content & Blog Strategy",
      "Email Marketing & Automation",
      "Analytics & Reporting",
      "Marketing Funnels",
      "Lead Generation",
      "Conversion Optimization",
      "Reputation & Google Business Profile",
    ],
    deliverables: [
      "SEO & content roadmap",
      "Automated lifecycle campaigns",
      "Conversion-optimized funnels",
      "Dashboards you'll actually read",
      "Monthly growth reporting",
    ],
    outcomes: [
      { metric: "+164%", label: "organic traffic" },
      { metric: "-42%", label: "cost per lead" },
      { metric: "6.4×", label: "return on spend" },
    ],
    process: [
      { title: "Audit", detail: "Full-funnel analysis to find the biggest levers." },
      { title: "Build", detail: "Content, technical fixes and automation put in place." },
      { title: "Convert", detail: "Funnels and CRO to turn traffic into pipeline." },
      { title: "Compound", detail: "Monthly iteration on what the data rewards." },
    ],
    technologies: ["GA4", "Ahrefs", "HubSpot", "Klaviyo", "Semrush", "Segment"],
    accent: "violet",
    pricingModel: PRICING_MODELS.RETAINER,
    packages: [
      {
        id: "digital-marketing-basic",
        serviceSlug: "digital-marketing",
        tier: PACKAGE_TIERS.BASIC,
        name: "Basic",
        tagline: "Get the technical foundation right.",
        priceLabel: "₹4,999",
        priceFrom: { amountMinor: 499900, currency: "INR" },
        cadence: "per month",
        features: [
          "Technical SEO audit & fixes",
          "On-page optimization",
          "2 content pieces / month",
          "Core analytics reporting",
        ],
        ctaLabel: "Choose Basic",
      },
      {
        id: "digital-marketing-standard",
        serviceSlug: "digital-marketing",
        tier: PACKAGE_TIERS.STANDARD,
        name: "Standard",
        tagline: "A real growth engine, compounding monthly.",
        priceLabel: "₹14,999",
        priceFrom: { amountMinor: 1499900, currency: "INR" },
        cadence: "per month",
        featured: true,
        features: [
          "Everything in Basic",
          "Content & blog strategy (4 posts/mo)",
          "Email marketing automation",
          "Conversion funnel optimization",
          "Monthly growth reporting",
        ],
        ctaLabel: "Choose Standard",
      },
      {
        id: "digital-marketing-premium",
        serviceSlug: "digital-marketing",
        tier: PACKAGE_TIERS.PREMIUM,
        name: "Premium",
        tagline: "A full-funnel program with a dedicated strategist.",
        priceLabel: "₹29,999",
        priceFrom: { amountMinor: 2999900, currency: "INR" },
        cadence: "per month",
        features: [
          "Everything in Standard",
          "Dedicated strategist",
          "Multi-channel campaigns",
          "Advanced attribution & dashboards",
          "Quarterly strategy reviews",
        ],
        ctaLabel: "Choose Premium",
      },
    ],
    addons: [
      {
        id: "digital-marketing-addon-content",
        serviceSlug: "digital-marketing",
        name: "Extra content pack",
        description: "4 additional long-form, SEO-optimized content pieces per month.",
        priceLabel: "₹25k/mo",
        priceFrom: { amountMinor: 2500000, currency: "INR" },
      },
      {
        id: "digital-marketing-addon-cro-sprint",
        serviceSlug: "digital-marketing",
        name: "Conversion optimization sprint",
        description: "A focused, one-off sprint testing and lifting your key conversion funnels.",
        priceLabel: "₹90k",
        priceFrom: { amountMinor: 9000000, currency: "INR" },
      },
    ],
    comparisonRows: [
      { feature: "Technical SEO & on-page", values: [true, true, true] },
      { feature: "Content cadence", values: ["2 posts/mo", "4 posts/mo", "8+ posts/mo"] },
      { feature: "Email marketing automation", values: [false, true, true] },
      { feature: "Dedicated strategist", values: [false, false, true] },
      { feature: "Advanced attribution & dashboards", values: [false, false, true] },
      { feature: "Quarterly strategy reviews", values: [false, false, true] },
    ],
  },
  {
    slug: "paid-advertising",
    categoryId: "brand-growth",
    index: "06",
    title: "Paid Advertising",
    tagline: "Performance media that pays for itself.",
    summary:
      "Full-funnel paid campaigns across Google, Meta, LinkedIn and YouTube — creative, targeting and tracking obsessed over ROAS.",
    outcome: "Profitable, scalable acquisition you can pour fuel on.",
    capabilities: [
      "Google & Meta Ads",
      "Instagram & Facebook Ads",
      "LinkedIn & YouTube Ads",
      "Performance Marketing",
      "Remarketing & PPC",
      "Shopping Ads",
      "Conversion Tracking",
      "A/B & Creative Testing",
    ],
    deliverables: [
      "Full-funnel media strategy",
      "Ad creative & copy testing",
      "Server-side conversion tracking",
      "Weekly optimization & scaling",
      "Transparent ROAS reporting",
    ],
    outcomes: [
      { metric: "6.4×", label: "return on ad spend" },
      { metric: "-38%", label: "cost per acquisition" },
      { metric: "24/7", label: "performance monitoring" },
    ],
    process: [
      { title: "Model", detail: "Unit economics and a channel plan that can scale profitably." },
      { title: "Launch", detail: "Creative, audiences and airtight conversion tracking." },
      { title: "Optimize", detail: "Daily bid, budget and creative iteration." },
      { title: "Scale", detail: "Winning campaigns pushed hard while ROAS holds." },
    ],
    technologies: ["Google Ads", "Meta", "LinkedIn", "GTM", "TripleWhale", "Looker"],
    accent: "cyan",
    pricingModel: PRICING_MODELS.RETAINER,
    packages: [
      {
        id: "paid-advertising-basic",
        serviceSlug: "paid-advertising",
        tier: PACKAGE_TIERS.BASIC,
        name: "Basic",
        tagline: "Launch on the one channel that matters most.",
        priceLabel: "₹1,999",
        priceFrom: { amountMinor: 199900, currency: "INR" },
        cadence: "per month + ad spend",
        features: [
          "One channel (Google or Meta)",
          "Campaign setup",
          "Conversion tracking",
          "Monthly reporting",
        ],
        ctaLabel: "Choose Basic",
      },
      {
        id: "paid-advertising-standard",
        serviceSlug: "paid-advertising",
        tier: PACKAGE_TIERS.STANDARD,
        name: "Standard",
        tagline: "Multi-channel performance, optimized weekly.",
        priceLabel: "₹9,999",
        priceFrom: { amountMinor: 999900, currency: "INR" },
        cadence: "per month + ad spend",
        featured: true,
        features: [
          "Everything in Basic",
          "Google + Meta + LinkedIn",
          "Creative & copy testing",
          "Server-side conversion tracking",
          "Weekly optimization",
        ],
        ctaLabel: "Choose Standard",
      },
      {
        id: "paid-advertising-premium",
        serviceSlug: "paid-advertising",
        tier: PACKAGE_TIERS.PREMIUM,
        name: "Premium",
        tagline: "Scaled acquisition with a dedicated media buyer.",
        priceLabel: "₹24,999",
        priceFrom: { amountMinor: 2499900, currency: "INR" },
        cadence: "per month + ad spend",
        features: [
          "Everything in Standard",
          "YouTube & Shopping ads",
          "Dedicated media buyer",
          "Daily optimization",
          "Transparent ROAS dashboard",
        ],
        ctaLabel: "Choose Premium",
      },
    ],
    addons: [
      {
        id: "paid-advertising-addon-channel",
        serviceSlug: "paid-advertising",
        name: "Additional ad channel",
        description: "Add another platform to your media mix, fully managed.",
        priceLabel: "₹25k/mo",
        priceFrom: { amountMinor: 2500000, currency: "INR" },
      },
      {
        id: "paid-advertising-addon-creative",
        serviceSlug: "paid-advertising",
        name: "Creative production sprint",
        description: "10 new ad creative assets, tested and ready to run.",
        priceLabel: "₹45k",
        priceFrom: { amountMinor: 4500000, currency: "INR" },
      },
    ],
    comparisonRows: [
      { feature: "Channels covered", values: ["1 channel", "3 channels", "5+ channels"] },
      { feature: "Server-side conversion tracking", values: [false, true, true] },
      { feature: "Creative & copy testing", values: [false, true, true] },
      { feature: "Dedicated media buyer", values: [false, false, true] },
      { feature: "Daily optimization", values: [false, false, true] },
      { feature: "ROAS dashboard", values: [false, true, true] },
    ],
  },
  {
    slug: "ai-automation",
    categoryId: "ai-continuity",
    index: "07",
    title: "AI Automation",
    tagline: "Put your busywork on autopilot.",
    summary:
      "Custom AI agents and workflow automation that qualify leads, answer customers and remove hours of manual work every week.",
    outcome: "More output, lower headcount, faster response times.",
    capabilities: [
      "Chatbots & AI Assistants",
      "CRM & Lead Qualification",
      "WhatsApp & Email Automation",
      "Business Workflow Automation",
      "OpenAI & Claude Integration",
      "Knowledge Base & Document AI",
      "Voice AI",
      "Custom AI Solutions",
    ],
    deliverables: [
      "Custom AI agent trained on your data",
      "Workflow automations across your tools",
      "Human-in-the-loop guardrails",
      "Analytics on deflection & savings",
      "Ongoing tuning & monitoring",
    ],
    outcomes: [
      { metric: "-63%", label: "manual workload" },
      { metric: "<30s", label: "response time" },
      { metric: "24/7", label: "always-on coverage" },
    ],
    process: [
      { title: "Map", detail: "Find the workflows where AI pays back fastest." },
      { title: "Build", detail: "Agents and automations wired into your stack." },
      { title: "Guard", detail: "Evaluations, guardrails and human review." },
      { title: "Improve", detail: "Continuous tuning as usage grows." },
    ],
    technologies: ["OpenAI", "Claude", "LangChain", "n8n", "Zapier", "Pinecone", "Twilio"],
    accent: "royal",
    pricingModel: PRICING_MODELS.TIERED,
    packages: [
      {
        id: "ai-automation-basic",
        serviceSlug: "ai-automation",
        tier: PACKAGE_TIERS.BASIC,
        name: "Basic",
        tagline: "Your first AI assistant, live in weeks.",
        priceLabel: "₹9,999",
        priceFrom: { amountMinor: 999900, currency: "INR" },
        cadence: "per project",
        features: [
          "One AI assistant / chatbot",
          "Trained on your docs",
          "Basic analytics",
          "2 weeks tuning",
        ],
        ctaLabel: "Choose Basic",
      },
      {
        id: "ai-automation-standard",
        serviceSlug: "ai-automation",
        tier: PACKAGE_TIERS.STANDARD,
        name: "Standard",
        tagline: "Automation wired directly into your workflow.",
        priceLabel: "₹34,999",
        priceFrom: { amountMinor: 3499900, currency: "INR" },
        cadence: "per project",
        featured: true,
        features: [
          "Everything in Basic",
          "CRM / lead qualification automation",
          "2–3 tool integrations",
          "Human-in-the-loop guardrails",
          "4 weeks tuning",
        ],
        ctaLabel: "Choose Standard",
      },
      {
        id: "ai-automation-premium",
        serviceSlug: "ai-automation",
        tier: PACKAGE_TIERS.PREMIUM,
        name: "Premium",
        tagline: "A custom, multi-agent AI platform.",
        priceLabel: "₹99,999",
        priceFrom: { amountMinor: 9999900, currency: "INR" },
        cadence: "per project",
        features: [
          "Everything in Standard",
          "Multi-agent workflows",
          "Voice AI",
          "Custom evaluations & monitoring",
          "Ongoing tuning retainer",
        ],
        ctaLabel: "Choose Premium",
      },
    ],
    addons: [
      {
        id: "ai-automation-addon-integration",
        serviceSlug: "ai-automation",
        name: "Additional integration",
        description: "Connect one more tool in your stack to the automation.",
        priceLabel: "₹40k",
        priceFrom: { amountMinor: 4000000, currency: "INR" },
      },
      {
        id: "ai-automation-addon-monitoring",
        serviceSlug: "ai-automation",
        name: "Monthly monitoring & tuning",
        description: "Ongoing evaluation, prompt tuning and guardrail upkeep.",
        priceLabel: "₹35k/mo",
        priceFrom: { amountMinor: 3500000, currency: "INR" },
      },
    ],
    comparisonRows: [
      { feature: "Tool integrations", values: ["—", "2–3 tools", "5+ tools"] },
      { feature: "CRM & lead qualification", values: [false, true, true] },
      { feature: "Human-in-the-loop guardrails", values: [true, true, true] },
      { feature: "Voice AI", values: [false, false, true] },
      { feature: "Multi-agent workflows", values: [false, false, true] },
      { feature: "Ongoing tuning", values: ["2 weeks", "4 weeks", "Retainer"] },
    ],
  },
  {
    slug: "maintenance-growth",
    categoryId: "ai-continuity",
    index: "08",
    title: "Maintenance & Growth",
    tagline: "A partner after launch, not a ghost.",
    summary:
      "Proactive monitoring, security and a monthly roadmap of improvements that keep your product fast, safe and always getting better.",
    outcome: "Peace of mind plus a product that compounds in value.",
    capabilities: [
      "Monthly Maintenance",
      "Monitoring & Backups",
      "Security Hardening",
      "Cloud Hosting (AWS, Cloudflare)",
      "Performance Optimization",
      "Analytics",
      "Feature Development",
      "Technical Support",
      "Continuous Improvement",
    ],
    deliverables: [
      "Proactive uptime & security monitoring",
      "Automated backups & recovery",
      "Monthly performance report",
      "A prioritized improvement roadmap",
      "Priority support SLA",
    ],
    outcomes: [
      { metric: "99.98%", label: "uptime" },
      { metric: "<2h", label: "response SLA" },
      { metric: "∞", label: "continuous improvement" },
    ],
    process: [
      { title: "Onboard", detail: "Audit, monitoring and backups established." },
      { title: "Protect", detail: "Security, updates and uptime handled for you." },
      { title: "Report", detail: "Monthly clarity on performance and priorities." },
      { title: "Grow", detail: "A steady cadence of shipped improvements." },
    ],
    technologies: ["AWS", "Cloudflare", "Vercel", "Datadog", "Sentry", "GitHub Actions"],
    accent: "violet",
    pricingModel: PRICING_MODELS.RETAINER,
    packages: [
      {
        id: "maintenance-growth-basic",
        serviceSlug: "maintenance-growth",
        tier: PACKAGE_TIERS.BASIC,
        name: "Basic",
        tagline: "The essentials, handled and monitored.",
        priceLabel: "₹1,999",
        priceFrom: { amountMinor: 199900, currency: "INR" },
        cadence: "per month",
        features: [
          "Uptime & security monitoring",
          "Automated backups",
          "Monthly report",
          "Standard support (<2 business days)",
        ],
        ctaLabel: "Choose Basic",
      },
      {
        id: "maintenance-growth-standard",
        serviceSlug: "maintenance-growth",
        tier: PACKAGE_TIERS.STANDARD,
        name: "Standard",
        tagline: "A partner actively improving your product.",
        priceLabel: "₹5,999",
        priceFrom: { amountMinor: 599900, currency: "INR" },
        cadence: "per month",
        featured: true,
        features: [
          "Everything in Basic",
          "Performance optimization sprints",
          "Priority support SLA (<2h)",
          "Feature development (up to 8h/mo)",
        ],
        ctaLabel: "Choose Standard",
      },
      {
        id: "maintenance-growth-premium",
        serviceSlug: "maintenance-growth",
        tier: PACKAGE_TIERS.PREMIUM,
        name: "Premium",
        tagline: "A dedicated engineer on call for your product.",
        priceLabel: "₹14,999",
        priceFrom: { amountMinor: 1499900, currency: "INR" },
        cadence: "per month",
        features: [
          "Everything in Standard",
          "Dedicated engineering hours (up to 24h/mo)",
          "Quarterly roadmap planning",
          "On-call incident response",
        ],
        ctaLabel: "Choose Premium",
      },
    ],
    addons: [
      {
        id: "maintenance-growth-addon-hours",
        serviceSlug: "maintenance-growth",
        name: "Additional engineering hours",
        description: "10 more hours of engineering time for features or fixes.",
        priceLabel: "₹35k",
        priceFrom: { amountMinor: 3500000, currency: "INR" },
      },
      {
        id: "maintenance-growth-addon-audit",
        serviceSlug: "maintenance-growth",
        name: "Annual security audit",
        description: "A full security review and hardening pass across your stack.",
        priceLabel: "₹75k",
        priceFrom: { amountMinor: 7500000, currency: "INR" },
      },
    ],
    comparisonRows: [
      { feature: "Uptime & security monitoring", values: [true, true, true] },
      { feature: "Support SLA", values: ["<2 business days", "<2 hours", "<2 hours + on-call"] },
      { feature: "Feature development hours", values: ["—", "8h/mo", "24h/mo"] },
      { feature: "Quarterly roadmap planning", values: [false, false, true] },
      { feature: "On-call incident response", values: [false, false, true] },
    ],
  },
];

export const getService = (slug: string) =>
  CATALOG_SERVICES.find((s) => s.slug === slug);

export const getServicesByCategory = (categoryId: string) =>
  CATALOG_SERVICES.filter((s) => s.categoryId === categoryId);

export const getPackage = (serviceSlug: string, packageId: string) =>
  getService(serviceSlug)?.packages.find((p) => p.id === packageId);
